# Generated by Django 6.0 on 2025-12-26 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
        ('meters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TariffRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('domestic', 'Domestic'), ('commercial', 'Commercial'), ('industrial', 'Industrial'), ('agricultural', 'Agricultural')], max_length=20)),
                ('slab_min', models.IntegerField(default=0)),
                ('slab_max', models.IntegerField(default=9999)),
                ('rate_per_unit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fixed_charge', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('subsidy_applicable', models.BooleanField(default=False)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tariff_rates',
                'ordering': ['category', 'slab_min'],
                'indexes': [models.Index(fields=['state', 'category'], name='tariff_rate_state_34b739_idx'), models.Index(fields=['effective_from'], name='tariff_rate_effecti_7d1055_idx')],
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('billing_period_start', models.DateField()),
                ('billing_period_end', models.DateField()),
                ('previous_reading', models.FloatField(default=0)),
                ('current_reading', models.FloatField(default=0)),
                ('units_consumed', models.FloatField(default=0)),
                ('base_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('energy_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subsidy', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='meters.meter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bills',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='bills_user_id_4297f1_idx'), models.Index(fields=['meter', '-created_at'], name='bills_meter_i_fcf7ce_idx'), models.Index(fields=['status'], name='bills_status_d22f38_idx')],
            },
        ),
    ]
