# Generated by Django 6.0 on 2025-12-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('energy_consumed', models.FloatField(default=0)),
                ('carbon_emitted', models.FloatField(default=0)),
                ('carbon_saved', models.FloatField(default=0)),
                ('trees_equivalent', models.FloatField(default=0)),
                ('renewable_energy_used', models.FloatField(default=0)),
                ('renewable_percentage', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'carbon_impacts',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ConsumptionPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_energy', models.FloatField(default=0)),
                ('avg_power', models.FloatField(default=0)),
                ('peak_power', models.FloatField(default=0)),
                ('peak_time', models.TimeField(blank=True, null=True)),
                ('off_peak_energy', models.FloatField(default=0)),
                ('efficiency_score', models.FloatField(default=0)),
                ('power_factor_avg', models.FloatField(default=0.95)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('potential_savings', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('insights', models.JSONField(default=dict)),
                ('recommendations', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'consumption_patterns',
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='EfficiencyScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('score', models.IntegerField(default=0)),
                ('power_factor_score', models.IntegerField(default=0)),
                ('load_profile_score', models.IntegerField(default=0)),
                ('peak_usage_score', models.IntegerField(default=0)),
                ('consistency_score', models.IntegerField(default=0)),
                ('total_energy', models.FloatField(default=0)),
                ('optimal_energy', models.FloatField(default=0)),
                ('wasted_energy', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'efficiency_scores',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='EnergyForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField(db_index=True)),
                ('forecast_hour', models.IntegerField(default=0)),
                ('predicted_energy', models.FloatField()),
                ('predicted_power', models.FloatField()),
                ('confidence_score', models.FloatField(default=0.0)),
                ('model_version', models.CharField(default='v1.0', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'energy_forecasts',
                'ordering': ['forecast_date', 'forecast_hour'],
            },
        ),
    ]
