# Generated by Django 6.0 on 2025-12-25 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('meters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbonimpact',
            name='meter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carbon_impacts', to='meters.meter'),
        ),
        migrations.AddField(
            model_name='consumptionpattern',
            name='meter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patterns', to='meters.meter'),
        ),
        migrations.AddField(
            model_name='efficiencyscore',
            name='meter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='efficiency_scores', to='meters.meter'),
        ),
        migrations.AddField(
            model_name='energyforecast',
            name='meter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='meters.meter'),
        ),
        migrations.AddIndex(
            model_name='carbonimpact',
            index=models.Index(fields=['meter', '-date'], name='carbon_impa_meter_i_4cb390_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='carbonimpact',
            unique_together={('meter', 'date')},
        ),
        migrations.AddIndex(
            model_name='consumptionpattern',
            index=models.Index(fields=['meter', '-period_end'], name='consumption_meter_i_2030c8_idx'),
        ),
        migrations.AddIndex(
            model_name='efficiencyscore',
            index=models.Index(fields=['meter', '-date'], name='efficiency__meter_i_1d6b5b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='efficiencyscore',
            unique_together={('meter', 'date')},
        ),
        migrations.AddIndex(
            model_name='energyforecast',
            index=models.Index(fields=['meter', 'forecast_date'], name='energy_fore_meter_i_3e1866_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='energyforecast',
            unique_together={('meter', 'forecast_date', 'forecast_hour')},
        ),
    ]
