# Generated by Django 6.0 on 2025-12-26 23:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('address', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('logo_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consumer_id', models.CharField(max_length=50, unique=True)),
                ('consumer_name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('connection_type', models.CharField(choices=[('residential', 'Residential'), ('agricultural', 'Agricultural'), ('commercial', 'Commercial'), ('industrial', 'Industrial')], default='residential', max_length=20)),
                ('connected_load_kw', models.DecimalField(decimal_places=2, default=2.0, max_digits=10)),
                ('meter_number', models.CharField(blank=True, max_length=50)),
                ('connection_date', models.DateField(blank=True, null=True)),
                ('connection_status', models.CharField(choices=[('active', 'Active'), ('disconnected', 'Disconnected'), ('suspended', 'Suspended'), ('pending', 'Pending Connection')], default='active', max_length=20)),
                ('gps_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('gps_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Houses',
                'ordering': ['consumer_id'],
            },
        ),
        migrations.CreateModel(
            name='Transformer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transformer_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('transformer_type', models.CharField(choices=[('distribution', 'Distribution Transformer'), ('pole_mounted', 'Pole Mounted'), ('pad_mounted', 'Pad Mounted'), ('substation', 'Substation Transformer')], default='distribution', max_length=20)),
                ('capacity_kva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('input_voltage', models.DecimalField(decimal_places=2, default=11000, max_digits=10)),
                ('output_voltage', models.DecimalField(decimal_places=2, default=230, max_digits=10)),
                ('efficiency_rating', models.DecimalField(decimal_places=2, default=98.5, max_digits=5)),
                ('max_houses', models.PositiveIntegerField(default=10)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('last_maintenance_date', models.DateField(blank=True, null=True)),
                ('gps_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('gps_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'Under Maintenance'), ('faulty', 'Faulty'), ('offline', 'Offline')], default='active', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['transformer_id'],
            },
        ),
        migrations.CreateModel(
            name='CompanyAdmin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(blank=True, max_length=50)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('can_manage_districts', models.BooleanField(default=False)),
                ('can_manage_alerts', models.BooleanField(default=True)),
                ('can_view_reports', models.BooleanField(default=True)),
                ('is_super_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='distribution.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company Admin',
                'verbose_name_plural': 'Company Admins',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20)),
                ('state', models.CharField(default='Gujarat', max_length=100)),
                ('total_capacity_kva', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='distribution.company')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ElectricityReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voltage_sent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('voltage_received', models.DecimalField(decimal_places=2, max_digits=10)),
                ('voltage_loss', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('voltage_loss_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('current_sent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('current_received', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('power_sent_kw', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('power_received_kw', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('power_loss_kw', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('power_loss_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('energy_sent_kwh', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('energy_received_kwh', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('energy_loss_kwh', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('power_factor', models.DecimalField(decimal_places=2, default=0.95, max_digits=4)),
                ('frequency', models.DecimalField(decimal_places=2, default=50.0, max_digits=5)),
                ('line_distance_meters', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('low_voltage', 'Low Voltage'), ('high_voltage', 'High Voltage'), ('loss_detected', 'Loss Detected'), ('theft_suspected', 'Theft Suspected'), ('equipment_fault', 'Equipment Fault')], default='normal', max_length=20)),
                ('is_anomaly', models.BooleanField(default=False)),
                ('reading_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='distribution.house')),
                ('transformer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='distribution.transformer')),
            ],
            options={
                'ordering': ['-reading_timestamp'],
            },
        ),
        migrations.AddField(
            model_name='house',
            name='transformer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='distribution.transformer'),
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('population', models.PositiveIntegerField(default=0)),
                ('total_households', models.PositiveIntegerField(default=0)),
                ('gps_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('gps_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villages', to='distribution.district')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='transformer',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transformers', to='distribution.village'),
        ),
        migrations.CreateModel(
            name='LossAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('voltage_drop', 'Voltage Drop'), ('power_loss', 'Power Loss'), ('theft_suspected', 'Theft Suspected'), ('equipment_fault', 'Equipment Fault'), ('overload', 'Overload'), ('line_fault', 'Line Fault')], max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('critical', 'Critical'), ('emergency', 'Emergency')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('investigating', 'Under Investigation'), ('resolved', 'Resolved'), ('false_alarm', 'False Alarm')], default='active', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('voltage_loss', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('voltage_loss_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('power_loss_kw', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('power_loss_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('estimated_financial_loss', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loss_alerts', to='distribution.district')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loss_alerts', to='distribution.house')),
                ('reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='distribution.electricityreading')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
                ('transformer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loss_alerts', to='distribution.transformer')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loss_alerts', to='distribution.village')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='electricityreading',
            index=models.Index(fields=['house', 'reading_timestamp'], name='distributio_house_i_4e2f40_idx'),
        ),
        migrations.AddIndex(
            model_name='electricityreading',
            index=models.Index(fields=['transformer', 'reading_timestamp'], name='distributio_transfo_6a961e_idx'),
        ),
        migrations.AddIndex(
            model_name='electricityreading',
            index=models.Index(fields=['status'], name='distributio_status_e619d5_idx'),
        ),
        migrations.AddIndex(
            model_name='electricityreading',
            index=models.Index(fields=['is_anomaly'], name='distributio_is_anom_29b003_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='village',
            unique_together={('district', 'code')},
        ),
        migrations.AddIndex(
            model_name='lossalert',
            index=models.Index(fields=['status', 'severity'], name='distributio_status_9aad13_idx'),
        ),
        migrations.AddIndex(
            model_name='lossalert',
            index=models.Index(fields=['transformer', 'created_at'], name='distributio_transfo_2d3b27_idx'),
        ),
        migrations.AddIndex(
            model_name='lossalert',
            index=models.Index(fields=['village', 'created_at'], name='distributio_village_e8f3d1_idx'),
        ),
        migrations.AddIndex(
            model_name='lossalert',
            index=models.Index(fields=['district', 'created_at'], name='distributio_distric_dee7c8_idx'),
        ),
    ]
